<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Rajkumars-MBP" failures="1" tests="2" name="Default test(failed)" time="0.032" errors="0" timestamp="2021-06-18T20:27:36 BST">
  <testcase classname="Test.RetryFailedTests" name="test2" time="0.005"/>
  <testcase classname="Test.RetryFailedTests" name="test3" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Test.RetryFailedTests.test3(RetryFailedTests.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="Test.RetryFailedTests" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
